const {test}=require('node:test'),assert=require('node:assert/strict');
const {loadTs}=require('../helpers/load-ts.cjs');
const fixtures=[['config-actions.ts',[['getBrandWebsiteConfig','view',[]],['saveBrandWebsiteConfig','edit',[{}]],['saveBrandWebsiteDesignSystem','edit',[{}]],['saveBrandWebsiteSeo','edit',[{},new File(['image'],'image.png',{type:'image/png'})]],['saveBrandWebsiteSocial','edit',[{}]],['saveBrandWebsiteTracking','edit',[{}]],['saveBrandWebsiteLegal','edit',[{}]]]],['home-actions.ts',[['getBrandWebsiteHome','view',[]],['saveBrandWebsiteHero','edit',[[]]],['saveBrandWebsitePromoTiles','edit',[[]]],['saveBrandWebsiteCampaignBanner','edit',[null]],['saveBrandWebsiteMenuPreview','edit',[[]]],['saveBrandWebsiteFooterCta','edit',[null]]]],['menu-settings-actions.ts',[['getBrandWebsiteMenuSettings','view',[]],['saveBrandWebsiteMenuSettings','edit',[{}]],['saveBrandWebsiteMenuHero','edit',[null]]]],['pages-actions.ts',[['listBrandWebsitePages','view',[]],['getBrandWebsitePage','view',['home']],['createBrandWebsitePage','create',[{slug:'home'}]],['updateBrandWebsitePage','edit',['home',{}]],['deleteBrandWebsitePage','delete',['home']]]]];
for(const [file,functions] of fixtures)test(`${file} rejects ungranted native brand operations before database or file storage`,async()=>{
 let reads=0,uploads=0;const calls=[];
 const api=loadTs('src/lib/superadmin/brand-website/'+file,{'server-only':{},'@/lib/access/orderfly-session':{requireOrderflyAccess:async(...args)=>{calls.push(args);throw Error('forbidden');}},'@/lib/firebase-admin':{getAdminDb:()=>{reads++;throw Error('Unexpected database access');}},'./storage':{uploadFileToFirebaseStorage:async()=>{uploads++;return 'https://fixture.test/image';}},'./brand-website-audit':{logBrandWebsiteAuditEntry:async()=>{}},'@/lib/developer/brand-website-api-logger':{logBrandWebsiteApiCall:async()=>{}}});
 for(const [name,permission,args] of functions){await assert.rejects(api[name]('foreign-brand',...args),/forbidden/);assert.deepEqual(calls.at(-1),['foreign-brand',null,'orderfly.website:'+permission]);}
 assert.equal(reads,0);assert.equal(uploads,0);
});

test('a permitted company website editor saves its brand menu hero without platform authority',async()=>{
 const scopes=[],writes=[];const api=loadTs('src/lib/superadmin/brand-website/menu-settings-actions.ts',{'server-only':{},'@/lib/access/orderfly-session':{requireOrderflyAccess:async(...args)=>scopes.push(args)},'@/lib/firebase-admin':{getAdminDb:()=>({doc:path=>({get:async()=>({exists:false}),set:async value=>writes.push({path,value})})}),admin:{firestore:{FieldValue:{serverTimestamp:()=> 'timestamp'}}}},'./brand-website-audit':{logBrandWebsiteAuditEntry:async()=>{}},'@/lib/developer/brand-website-api-logger':{logBrandWebsiteApiCall:async()=>{}}});
 await api.saveBrandWebsiteMenuHero('own-brand',null);assert.deepEqual(scopes,[['own-brand',null,'orderfly.website:edit']]);assert.equal(writes.length,1);assert.equal(writes[0].path,'/brands/own-brand/website/menuSettings');assert.equal(writes[0].value.hero,null);
});
